# -*- coding: utf-8 -*-
"""car_plate_detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10dAqExQONTkXK5I13x2l8E_EjoyWXPbt
"""

from google.colab import drive
drive.mount('/content/gdrive')

!git clone https://github.com/WongKinYiu/yolov7.git

!pip install -r /content/gdrive/MyDrive/Colab_Notebooks/yolov7/requirements.txt

"""**RoboFlow**"""

!pip install roboflow

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/gdrive/MyDrive/Colab_Notebooks/yolov7

from roboflow import Roboflow
rf = Roboflow(api_key="FB9PMK8fLhkrxhudjsK1")
project = rf.workspace("object-detection-6aghk").project("anpr_ir-hpxjh")
dataset = project.version(1).download("yolov7")

"""**WandB**"""

# Weights & Biases
!pip install -q wandb
import wandb
wandb.login()

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# wget -P /content/gdrive/MyDrive/Colab_Notebooks/yolov7 https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7.pt

"""***Training***"""

# fine-tuning on a pre-trained model of yolov7

!python /content/gdrive/MyDrive/Colab_Notebooks/yolov7/train.py --batch 16 --cfg /content/gdrive/MyDrive/Colab_Notebooks/yolov7/cfg/training/yolov7.yaml --epochs 40 --device 0 --data /content/gdrive/MyDrive/Colab_Notebooks/yolov7/ANPR_ir-1/data.yaml --weights /content/gdrive/MyDrive/Colab_Notebooks/yolov7/yolov7.pt

from IPython.display import Image

Image('/content/gdrive/MyDrive/Colab_Notebooks/yolov7/runs/train/exp/F1_curve.png')

!python /content/gdrive/MyDrive/Colab_Notebooks/yolov7/detect.py --weights /content/gdrive/MyDrive/Colab_Notebooks/yolov7/runs/train/exp/weights/best.pt --conf 0.1 --source /content/gdrive/MyDrive/Colab_Notebooks/yolov7/ANPR_ir-1/test/images